### ISSUE TITLE
localStorage 공통함수 작성

### ISSUE THREAD

**Issue by Jadest13** [FunD-StockProject/StockProject-Frontend#11]
## 📒 설명
 유틸성 증가를 위한 localStorage 공통함수 작성

## ✅ TO-DO
- [x]  localStorage 공통함수 구현
- [x]  localStorage 사용한 코드 리팩토링

## 🔔 기타
 MainLayout.tsx 내 오래된 검색어 재 입력시 순서 앞으로 가져옴

**Comment by Jadest13** [comment]
@durumi99 확인 후 issue close 해주삼

**Comment by durumi99** [comment]
ok
